'use strict';
const app = document.querySelector('#app');
const scene = document.querySelector('#scene');
const panel = document.querySelector('#panel');
const number = n => new Intl.NumberFormat('ar-EG', {useGrouping:false}).format(n);
const clean = text => text.replace(/[\uFB50-\uFDCF]\s*$/u, '').trim();
let ui, index, surahs, data, depth = 1, scope = null, stops = [], extras = [], general = [], current = null;
function el(tag, cls, text) { const node = document.createElement(tag); if(cls) node.className = cls; if(text != null) node.textContent = text; return node; }
function button(text, action, cls, label) { const b = el('button', cls, text); b.type = 'button'; if(label) b.setAttribute('aria-label',label); b.addEventListener('click',action); return b; }
function ownAyahs() { return data.ayahs.filter(a => a.key.startsWith(data.surah.no + ':')); }
function ayah(key) { return data.ayahs.find(a => a.key === key); }
function quran(keys, cls = 'quran') { const box = el('div',cls); keys.forEach(key => { const a = ayah(key); if(!a) return; box.append(document.createTextNode(clean(a.text)), el('span','ayah-medallion',number(a.no)),document.createTextNode(' ')); }); return box; }
function icon(key) { const i = el('span','sigil',ui.icons[key].symbol); i.style.color = ui.icons[key].color; i.title = ui.icons[key].label; return i; }
function badge(key) { const b = el('span','badge',ui.badges[key].label); b.style.color = ui.badges[key].color; return b; }
function segments(items) { const fragment = document.createDocumentFragment(); items.forEach(s => {
 if(s.t === 'text') fragment.append(document.createTextNode(s.v));
 if(s.t === 'ayah') { const a = ayah(s.key); if(a) fragment.append(el('span','inline-ayah',clean(a.text))); }
 if(s.t === 'quote') fragment.append(el('span','quotation',s.v));
 if(s.t === 'term') fragment.append(button(s.v,()=>showRecords([s.record],ui.reader.open_term),'term',ui.reader.open_term + ': ' + s.v));
 if(s.t === 'mark') { const b = button('',()=>showRecords(s.records),'mark',ui.panel.title); const keys = new Set(); s.records.forEach(id => data.records[id].icons.forEach(k=>keys.add(k))); ui.icon_order.filter(k=>keys.has(k)).forEach(k=>b.append(icon(k))); fragment.append(b); s.records.forEach(id=>{ const key=data.records[id].badge; if(key && key!=='thabit') fragment.append(badge(key)); }); }
 }); return fragment; }
function renderBlock(b) { if(b.type==='ayah') return quran(b.keys); if(b.type==='heading') return el('h3','scene-title',b.text); if(b.type==='paragraph') { const p=el('p','prose '+(b.role==='transmission'?'transmission':'')); p.append(segments(b.segments)); return p; } if(b.type==='details') { const d=el('details','detail-item'); const s=el('summary'); s.append(segments(b.title)); const body=el('div','detail-body'); b.blocks.forEach(x=>body.append(renderBlock(x))); d.append(s,body); return d; } }
function detailsKeys(b) { const ids=b.title.filter(s=>s.t==='mark').flatMap(s=>s.records); const keys=ids.flatMap(id=>data.records[id].ayah_keys); return [...new Set(keys)].filter(k=>k.startsWith(data.surah.no+':')); }
function parseLevel() { stops=[]; extras=[]; general=[]; let last=null; for(const b of data.levels.find(l=>l.depth===depth).blocks) { if(b.type==='ayah') continue; if(b.type==='paragraph' && b.title) { last={title:b.title,keys:b.ayahs,passage:b.passage,blocks:[b]}; stops.push(last); } else if(b.type==='details') { const keys=detailsKeys(b); extras.push({title:b.title,keys:keys.length?keys:[ownAyahs()[0].key],blocks:[b],detail:true}); last=null; } else if(last) last.blocks.push(b); else general.push(b); } }
function inScope(item) { if(!scope) return true; const p=data.passages.find(p=>p.id===scope); return item.keys.some(k=>+k.split(':')[1]>=+p.from.split(':')[1]&&+k.split(':')[1]<=+p.to.split(':')[1]); }
function allItems() { return [...stops,...extras].filter(inScope).sort((a,b)=>+a.keys[0].split(':')[1]-+b.keys[0].split(':')[1]); }
function sigilsFor(item) { const ids=item.detail?item.title.filter(s=>s.t==='mark').flatMap(s=>s.records):item.blocks.flatMap(b=>(b.segments||[]).filter(s=>s.t==='mark').flatMap(s=>s.records)); const keys=new Set(ids.flatMap(id=>data.records[id].icons)); const box=el('span','sigils'); ui.icon_order.filter(k=>keys.has(k)).forEach(k=>box.append(icon(k))); return box; }
function branch(item) { if(item.detail) {const box=el('div','branch detail-branch');const body=el('div','question');body.append(segments(item.title));box.append(body,button('+',()=>openStop(item),'arrow','Open depth item'));return box;} const b=button('',()=>openStop(item),'branch');const body=el('span','question',item.title);body.append(sigilsFor(item));b.append(body,el('span','arrow','←'));return b; }
function render() {
 parseLevel(); app.replaceChildren(); app.setAttribute('aria-busy','false');
 const hero=el('header','hero'); const top=el('div','topbar'); top.append(el('span','brand',ui.app_name)); const actions=el('div','top-actions'); actions.append(button('ⓘ',showAbout,'icon-button','About this reading experience'),button('◇',showLegend,'icon-button',ui.legend.show)); top.append(actions); hero.append(top);
 const chooser=el('label','surah-select',ui.reader.surahs_title); const select=el('select'); select.setAttribute('aria-label',ui.reader.surahs_title); index.surahs.filter(s=>[108,93].includes(s.no)).forEach(s=>{const o=el('option',null,s.name);o.value=s.no;o.selected=s.no===data.surah.no;select.append(o);}); select.addEventListener('change',()=>{data=surahs[select.value];scope=null;render();}); chooser.append(select); hero.append(chooser,el('h1',null,data.surah.name),el('p','tagline',ui.tagline));
 const mini=el('nav','mini-map');mini.setAttribute('aria-label',ui.reader.ayahs_title);ownAyahs().forEach(a=>{const b=button(number(a.no),()=>{document.getElementById('station-'+a.no)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});if(scope){scope=null;render();document.getElementById('station-'+a.no)?.scrollIntoView({block:'center'});}},scope?'':'active',ui.reader.ayahs_title+' '+number(a.no));mini.append(b);});hero.append(mini);app.append(hero);
 const depthBox=el('section','depth-wrap');depthBox.append(el('p','eyebrow',ui.reader.choose_depth));const depths=el('div','depths');ui.levels.forEach(l=>{const b=button('',()=>{depth=l.depth;render();},null,l.name);b.setAttribute('aria-pressed',l.depth===depth);b.append(el('span','depth-dot','·'.repeat(l.depth+1)),el('span',null,l.name));depths.append(b);});depthBox.append(depths);app.append(depthBox);
 const overview=el('section','overview');const heading=el('div','view-heading');heading.append(el('h2',null,ui.reader.map_view),button(ui.reader.read_continuous,openContinuous,'continuous'));overview.append(heading);
 if(data.passages?.length) {const tabs=el('nav','passage-tabs');tabs.setAttribute('aria-label',ui.reader.passages_title);const all=button(ui.reader.map_view,()=>{scope=null;render();});all.setAttribute('aria-pressed',!scope);tabs.append(all);data.passages.forEach((p,i)=>{const b=button(number(i+1)+' · '+p.title,()=>{scope=p.id;render();});b.setAttribute('aria-pressed',scope===p.id);tabs.append(b);});overview.append(tabs);}
 if(general.length) {const b=button('',()=>openGeneral(),'branch');b.append(el('span','question',general.find(b=>b.type==='heading')?.text||ui.levels[depth].name),el('span','arrow','←'));overview.append(b);}
 const ribbon=el('div','ribbon');let visible=ownAyahs();if(scope){const p=data.passages.find(p=>p.id===scope);visible=visible.filter(a=>a.no>=+p.from.split(':')[1]&&a.no<=+p.to.split(':')[1]);}
 visible.forEach((a,i)=>{const passage=data.passages?.find(p=>p.from===a.key);if(passage){const ch=el('div','chapter');ch.append(el('span','chapter-no',number(data.passages.indexOf(passage)+1)),el('span','chapter-title',passage.title),el('span','chapter-range',number(+passage.from.split(':')[1])+' — '+number(+passage.to.split(':')[1])),button('↗',()=>openPassage(passage),null,'Read this passage'));ribbon.append(ch);}
 const station=el('article','station');station.id='station-'+a.no;station.style.animationDelay=Math.min(i*35,180)+'ms';station.append(button(number(a.no),()=>openAyah(a),'number',ui.reader.ayahs_title+' '+number(a.no)),button(clean(a.text),()=>openAyah(a),'ayah-preview',ui.reader.ayahs_title+' '+number(a.no)));[...stops,...extras].filter(s=>s.keys[0]===a.key).forEach(s=>station.append(branch(s)));ribbon.append(station);});overview.append(ribbon);app.append(overview);
 const foot=el('footer','footer');foot.append(button('◇',showLegend,null,ui.legend.show),el('span',null,ui.disclosure.scripture));app.append(foot);
}
function dialogBar(title,target) { const bar=el('div','dialog-bar');bar.append(el('span',null,title),button('×',()=>target.close(),'close',ui.panel.close));return bar; }
function showScene(title,body) { const content=document.getElementById('scene-content');content.replaceChildren(dialogBar(title,scene),body); if(!scene.open)scene.showModal();scene.scrollTop=0; }
function sceneBody() { return el('div','scene-body'); }
function openStop(item) {current=item;const body=sceneBody();body.append(quran(item.keys,'scene-ayah quran'));if(!item.detail) body.append(el('h2','scene-title',item.title));item.blocks.forEach(b=>body.append(renderBlock(b)));const items=allItems(),i=items.indexOf(item),next=items[i+1];if(next){const teaser=el('div','next-preview');teaser.append(el('span',null,ui.reader.next_stop),el('div',null,next.detail?next.title.filter(s=>s.v).map(s=>s.v).join(''):next.title));body.append(teaser);}const nav=el('nav','scene-nav');const prev=button('→ '+ui.reader.previous_stop,()=>openStop(items[i-1]));prev.disabled=i<=0;const onward=button(ui.reader.next_stop+' ←',()=>openStop(next));onward.disabled=!next;nav.append(prev,onward);body.append(nav);showScene(ui.levels[depth].name,body); }
function openAyah(a) {const body=sceneBody();body.append(quran([a.key],'scene-ayah quran'));const items=[...stops,...extras].filter(s=>s.keys.includes(a.key));items.forEach(s=>body.append(branch(s)));if(!items.length)body.append(button(ui.reader.read_continuous,openContinuous,'branch'));showScene(ui.reader.ayahs_title+' '+number(a.no),body);}
function openGeneral() {const body=sceneBody();general.forEach(b=>body.append(renderBlock(b)));showScene(ui.levels[depth].name,body);}
function openContinuous() {const body=sceneBody();if(scope) {openPassage(data.passages.find(p=>p.id===scope));return;}data.levels.find(l=>l.depth===depth).blocks.forEach(b=>{if(b.title&&b.type==='paragraph')body.append(el('h2','scene-title',b.title));body.append(renderBlock(b));});showScene(ui.reader.read_continuous,body);}
function openPassage(p) {const keys=ownAyahs().filter(a=>a.no>=+p.from.split(':')[1]&&a.no<=+p.to.split(':')[1]).map(a=>a.key);const body=sceneBody();body.append(el('h2','scene-title',p.title));const source=button('',()=>showRecords(p.records),'mark',ui.panel.title);p.records.flatMap(id=>data.records[id].icons).filter((k,i,a)=>a.indexOf(k)===i).forEach(k=>source.append(icon(k)));body.append(source,quran(keys,'scene-ayah quran'));[...stops,...extras].filter(s=>s.keys.some(k=>keys.includes(k))).forEach(s=>body.append(branch(s)));showScene(ui.reader.passages_title,body);}
function showRecords(ids,title=ui.panel.title) { const content=document.getElementById('panel-content');content.replaceChildren(dialogBar(title,panel));ids.forEach(id=>{const r=data.records[id],box=el('section','record');r.icons.forEach(k=>box.append(icon(k)));box.append(el('span','label',ui.panel.claim),el('h3',null,r.claim));if(r.badge)box.append(badge(r.badge));else box.append(el('span','badge',ui.panel.no_badge));if(r.status_text)box.append(el('p','status',r.status_text));r.evidence.forEach(e=>{const ev=el('div','evidence');const field=(label,value)=>{if(value)ev.append(el('span','label',label),el('div',null,value));};ev.append(icon(e.icon));field(ui.panel.source,e.source_title);field(ui.panel.author,e.author);field(ui.panel.locator,e.locator);ev.append(el('span','label',ui.panel.quote),el('blockquote',null,e.quote));e.rulings.forEach(rule=>{field(ui.panel.ruling,rule.text);field(ui.panel.ruler,rule.ruler);field(ui.panel.locator,rule.where);});if(e.link_strength)field(ui.link_strength.note,ui.link_strength[e.link_strength]);if(e.url&&/^https?:\/\//.test(e.url)){const a=el('a',null,ui.panel.open_source+' ↗');a.href=e.url;a.target='_blank';a.rel='noopener noreferrer';ev.append(a);}box.append(ev);});content.append(box);});if(!panel.open)panel.showModal();panel.scrollTop=0;}
function showLegend() {const content=document.getElementById('panel-content');content.replaceChildren(dialogBar(ui.legend.title,panel));ui.icon_order.forEach(k=>{const row=el('div','legend-row');const symbol=icon(k);symbol.className='legend-symbol';const body=el('div');body.append(el('strong',null,ui.icons[k].label),el('p',null,ui.icons[k].meaning));row.append(symbol,body);content.append(row);});content.append(el('div','record',ui.legend.badges_title));Object.keys(ui.badges).forEach(k=>{const row=el('div','legend-row');row.append(badge(k),el('p',null,ui.badges[k].meaning));content.append(row);});panel.showModal();panel.scrollTop=0;}
function showAbout() {const content=document.getElementById('panel-content');content.replaceChildren(dialogBar(ui.app_name,panel));const box=el('div','record');Object.values(ui.disclosure).forEach(s=>box.append(el('p','prose',s)));box.append(el('p','status',ui.privacy_line));content.append(box);panel.showModal();}
[scene,panel].forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
async function boot() {try {const paths=['../../../content/ui.ar.json','../../../content/export/index.json','../../../content/export/surah-108.json','../../../content/export/surah-93.json'];const results=await Promise.all(paths.map(async path=>{const response=await fetch(path);if(!response.ok)throw new Error('Content unavailable: '+path);return response.json();}));[ui,index]=results;surahs={108:results[2],93:results[3]};data=surahs[108];render();}catch(error){app.replaceChildren(el('p','record','Unable to load content. Serve this page from the repository root.'));app.setAttribute('aria-busy','false');console.error(error);}}
boot();
