#!/usr/bin/env python3
"""Check that docs/06-product/safety-test-set.md and tools/data/eval/safety_cases.json
carry the same case IDs, the same count and the same levels.

The Arabic file's case sections were generated by a script that was not saved, so
the two files are kept in sync by hand; run this after editing either one.

Usage: python3 tools/check_safety_cases.py
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MD = ROOT / "docs" / "06-product" / "safety-test-set.md"
JS = ROOT / "tools" / "data" / "eval" / "safety_cases.json"
LEVELS = {"أ": "(أ)", "ب": "(ب)", "ج": "(ج)", "د": "(د)"}


def main() -> int:
    md = MD.read_text(encoding="utf-8")
    cases = json.loads(JS.read_text(encoding="utf-8"))["cases"]
    md_ids = re.findall(r"^### ((?:rasmi|huda)-\d+):", md, re.M)
    js_ids = [c["id"] for c in cases]
    errors = []
    if len(md_ids) != len(js_ids):
        errors.append(f"count differs: md={len(md_ids)} json={len(js_ids)}")
    for name, ids in (("md", md_ids), ("json", js_ids)):
        dup = {i for i in ids if ids.count(i) > 1}
        if dup:
            errors.append(f"duplicate ids in {name}: {sorted(dup)}")
    if set(md_ids) != set(js_ids):
        errors.append(f"only in md: {sorted(set(md_ids) - set(js_ids))}; "
                      f"only in json: {sorted(set(js_ids) - set(md_ids))}")
    # level per case: the "المستوى" line of each md section vs the json level
    sections = re.split(r"^### ", md, flags=re.M)[1:]
    for sec in sections:
        m = re.match(r"((?:rasmi|huda)-\d+):", sec)
        if not m:
            continue
        cid = m.group(1)
        lv = re.search(r"^- \*\*المستوى:\*\* (.+)$", sec, re.M)
        case = next((c for c in cases if c["id"] == cid), None)
        if not lv or not case:
            continue
        line = lv.group(1)
        want = LEVELS.get(case["level"]) if case["level"] else "لا ينطبق"
        if not line.startswith(want):
            errors.append(f"{cid}: md level line {line[:20]!r} vs json {case['level']!r}")
    if errors:
        print("MISMATCH")
        for e in errors:
            print(" -", e)
        return 1
    print(f"OK: {len(js_ids)} cases, same ids and levels in both files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
